drinkingGameRules = ('A:	Never Have I Ever',
'2:	Two Sips',
'3:	Hand Out 3 Sips',
'4:	Question Master',
'5:	Sneaky Eyes',
'6:	Thumb',
'7:	Hitler',
'8:	Story',
'9:	Rule',
'10:	Category',
'J:	Two Truths, One Lie',
'Q:	Whore',
'K:	Jump Into The Snow')